### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by topdot** [intelligo-mn/intelligo.store#16]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
   corresponds to your MySQL server version for the right syntax to use near 'created_at) null, `updated_at` timestam
  p(created_at) null) default character set' at line 1 (SQL: create table `password_resets` (`email` varchar(255) not
   null, `token` varchar(255) not null, `created_at` timestamp(created_at) null, `updated_at` timestamp(created_at) n
  ull) default character set utf8 collate utf8_unicode_ci engine = InnoDB)

**Comment by tortuvshin** [comment]
https://laravel-news.com/laravel-homestead-now-with-mysql-5-7-and-node-5-0

**Comment by uniquechukwuma** [comment]
I have this error and dont have solution to it

**Comment by kresnabudi** [comment]
Just change timestamps to timestamp
`Schema::create('password_resets', function (Blueprint $table) {
            $table->engine = "InnoDB";
            $table->string('email')->index();
            $table->string('token')->index();
            $table->timestamp('created_at');
        });`
